# Generated by Django 6.0 on 2026-01-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('no_helmet', 'No Helmet'), ('overload', 'Overload')], max_length=20)),
                ('plate_text', models.CharField(blank=True, max_length=32)),
                ('confidence', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='snapshots/')),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
